language: java

sudo: false

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8


install: true


script:
  - ./gradlew check
  - ./gradlew sonarqube \
    -Dsonar.projectKey=GOF2_gmail-client \
    -Dsonar.organization=gof2 \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=f41b1e3042c9235ccba6eb25f3265d35e60b68a1
  - sonar-scanner



cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



addons:
  sonarcloud:
    organization: "gof2"
    token:
      secure: "YhB27a5uY4ugynrsJKPYtmCviBM05a7Ivu2qOUPXyenYD9aJU77CRBVeD1k1sg7gWsRzVroZiu8LkRYhsrpP1pOa7MVNUpaXlqdW20jZnq80FNG1qyN0SfynqaNMOBYDzVr1W0vI+oisa9mo84ixd2I6rTxtvtHBbs0xSrEjne/W09nw64BZ9+7dOis8kFTnn5EbjvySf4HfYwAdYNnP90p/B6mx8AyK+SyA6tGxmKMf2yVoJfLqYm9LGrWBXYmGIvnNfaJX2Rdu1A95D87/AHqjW2XVpWlE4FGe1fbiF0wZjLpSsDWrQ0+a3sgUmMxjFUTWdxxESgEGXVxtwNQy7c9hhbpyJ1U2sNH48PLtMlPCDeRX19x18XVdqXKY1QVXoC9TCWeux6LcQlmjwxsruOzgshGqRle+YSdIuoQ/RNZ8XZ4cUUpo1WTydrd9OnTX0K8GDO2A1NnvpdSaOHQDg+PpP767R+zEK2XgJnQbe9YBJj/CVH+RzLFQ7BdXllllGCQcBTawuOq418qL4DL6ERPmdatO+x8QiqO3e2L8po3M22YpBcRjB44mDZUxxAeMB+2Rxqj2MhtJVubX7sqxFrahq3FYZdJCpZIqapRATndZvz+x0YAVGiMT6eee3ynpUyDx2XrzSqZSzLBHzmN/NW8bJOaJa99TuHrm8v2VoZY="
