language: java

sudo: false

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8


install: true


script:
  - ./gradlew check
  - sonar-scanner





cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



addons:
  sonarcloud:
    organization: "gof2"
    token:
      secure: "cKRCGqE8rBBpE+DMyCpCYvPlLry1lVWGt9sH8i++xmOUCKILlOoWDKJkMQV2Tm1JzGzARlr9vELu1O1La/idkTQgWlQu9nlda6QmFkV5eW1E/bcrSS9IYUy2ALRPNi6DlIwG3v4wNDiJKRW9fAbBZQxi/YudWtHlZkUkLSqNYw7VDcgpk55+GQb02aWxCVwyLMWtkC7/8gxxVHgXaJ/1VVXeqCHcHidUNVJJyhUm3aJ0SkvupVNFBBcsqG0NzKcCIrZpn6ZvPcjiW0Xgc8BVNYv3VTwD9neFPyeUjCXN32omPJfVXypf/65gTBO6P6xEo3oiSYwBT3HumMMXJq07AMeDy38wqUhs+JdCJymMqyyiCeyY/djErKs1hhqg/6LvBIJ0YiZhNV/BS3VqoFqH6C69X90eRhSF6ZW4ck1qyF1skpB0uJPEr3bdUCahY5fiY8L+RxW2tEuw8y2m8PM+P8HNaiHO6Zw1uSgATsSEzeBeDPj8d5MZS5/L8ZdrKqaErE/DTJNXEdbEDQCa48CN9iAvZQomafKPsSIg7HZICzd0RXfo2odMiAUpJyrNY4347S1XkyiFpM3GMxutcgdBu1wscfYnVmguNsuM7yctoQ5CMTkDTKpnVXkXwNiagipKlxHp+3FL5R8clpZYsA3uDjtkZusQaMZkaNT4RT5ED/I="