language: java

sudo: false

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8


install: true


script:
  - ./gradlew check
  - sonar-scanner



cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



addons:
  sonarcloud:
    organization: "gof2"
    token:
      secure: "MfOha8gxNiS0J4Lvt3FtOeyRkJyZ9w3vlCw0Ubm5oMJQBtFOfBhBxi5CGECvjG6/IzTTJpB3CkumGIs+VzeQWofWMN/Z2St8M4d47yUc/qC40fGHlX/wyA6hJ+BcSyf0AyaT8hTT3jgrGYKNidqiNOwGZzkzHIJ7Ec3bm34rLTFXQ+oBdQxmu0AP8dE2cih2sEdwX/Q/7/5wAovC4QiCHc+E74dLCwa5t6LDump/TUNGneeUnkgU6Yj4ogjmJD2+AuM4c5VDOJgYH+hEPMTplmpZG6prz8ZRT6OgZolWzcdHG2rv6UL0qsAGlMo4aVx3LVkdcpS4eQLtNnbG6PbnFus+wJUQb7aGJU3why+UdXVZflA18J7+ndFI3BpbzBotUiBne7fHO9AthLPqLnwG9HrDrPhp74E9HVU93Ppjef7SI8D9Ub8Detk4nGxFLiPNtuaNjUq2yj/27meoD+BQ106m5tBdgw3pTwBgYKmnxwn7CTAM2MTDWAJPCD8ArJwLceCiyCcGq4K0XVVocfn1HFUQBCaQ8keXtI0CB3SHUtUQSoXuqZk4BuUTgNeQ+UPIxn5MZzBzyaY9uSAS5HYWC0wWuzCiZtWZyzPVhD9dHvFk83mMQZhj/bxubuo1s7oNyRMg7fq9Cfo5KuHsDR8mf4ykaJ54pb7dN9xgeDTo150="